name: Validate PR

on:
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '*.md'

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@3cfe3a4abbb849e10058ce4af15d205b6da42804 # v3.7.1
        with:
          version: v1.54.2
  unit_tests:
    name: Unit-Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Unit Tests
        run: make test
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Build All
        run: make all
